// Data cho biểu đồ
export const chartData = [
  { name: "Database", daNop: 26, chuaNop: 8 },
  { name: "Lập trình Wed", daNop: 12, chuaNop: 24 },
  { name: "ASP.NET", daNop: 26, chuaNop: 20 },
  { name: "Lập trình Mobile", daNop: 14, chuaNop: 38 },
]

// Data thông báo
export const notifications = [
  { id: 1, title: "Đã phân công giảng viên" },
  { id: 2, text: "Đã có thay đổi về lịch họp của bộ môn. Thời gian cuộc họp bị dời sang 14h chiều nay tại phòng 204" },
  { id: 3, text: "Đã có thay đổi về lịch họp của bộ môn. Thời gian cuộc họp bị dời sang 14h chiều nay tại phòng 204" },
  { id: 4, text: "Đã có thay đổi về lịch họp của bộ môn. Thời gian cuộc họp bị dời sang 14h chiều nay tại phòng 204" },
  { id: 5, text: "Đã có thay đổi về lịch họp của bộ môn. Thời gian cuộc họp bị dời sang 14h chiều nay tại phòng 204" },
]

// Data thông báo gần đây cho trang tổng quan
export const recentNotifications = [
  {
    id: 1,
    title: "Đã phân công giảng viên",
    content: "Đã phân công giảng viên mới cho lớp Database. Vui lòng kiểm tra và xác nhận.",
    timeAgo: "2 giờ trước",
    daDoc: true,
  },
  {
    id: 2,
    title: "Thay đổi lịch họp",
    content: "Đã có thay đổi về lịch họp của bộ môn. Thời gian cuộc họp bị dời sang 14h chiều nay tại phòng 204",
    timeAgo: "3 giờ trước",
    daDoc: false,
  },
  {
    id: 3,
    title: "Thay đổi lịch họp",
    content: "Đã có thay đổi về lịch họp của bộ môn. Thời gian cuộc họp bị dời sang 14h chiều nay tại phòng 204",
    timeAgo: "5 giờ trước",
    daDoc: true,
  },
  {
    id: 4,
    title: "Phản hồi mới từ học viên",
    content: "Học viên Trần Thị B đã gửi phản hồi về bài giảng Lập trình Web. Vui lòng xem xét và phản hồi.",
    timeAgo: "1 ngày trước",
    daDoc: true,
  },
]

// Data thông báo chi tiết
export const thongBaoData = [
  {
    id: 1,
    tieuDe: "Thông báo lịch họp Khoa tháng 11/2025",
    nguoiGui: "TS. Nguyễn Hải Trường",
    chucVu: "Trưởng khoa CNTT",
    thoiGian: "21/12/2025 19:00",
    noiDung:
      "Kính gửi các thầy cô giảng viên, Khoa Công nghệ thông tin trân trọng thông báo lịch họp định kỳ tháng 11/2025 như sau: - Thời gian: 14h00, Thứ Sáu, ngày 15/11/2025 - Địa điểm: Phòng họp 204, Cơ sở 1 - Nội dung: Báo cáo tình hình giảng dạy, thảo luận về chương trình đào tạo mới. Rất mong các thầy cô sắp xếp thời gian tham dự đầy đủ.",
    doiTuong: "Tất cả giảng viên",
    phamVi: "Bộ môn",
    daDoc: false,
  },
  {
    id: 2,
    tieuDe: "Thay đổi thông báo vì lí do gửi ngu của Phúc - Trưởng khoa",
    nguoiGui: "Phúc",
    chucVu: "Trưởng khoa",
    thoiGian: "21/12/2025 19:00",
    noiDung: "Thay đổi lịch thi của môn lập trình web sang ngày 21/02/2030",
    doiTuong: "Tất cả sinh viên",
    phamVi: "Bộ môn",
    daDoc: true,
  },
  {
    id: 3,
    tieuDe: "Thay đổi lịch thi môn lập trình Web • ADMIN",
    nguoiGui: "ADMIN",
    chucVu: "",
    thoiGian: "21/12/2025 19:00",
    noiDung: "Thay đổi lịch thi của môn lập trình web sang ngày 21/02/2030",
    doiTuong: "Tất cả sinh viên",
    phamVi: "Bộ môn",
    daDoc: true,
  },
]

// Danh sách bộ môn/phạm vi
export const phamViList = ["Bộ môn", "Khoa CNTT", "Khoa Điện", "Khoa Cơ Khí", "Tất cả"]

// Data danh sách lớp học
export const classesData = [
  {
    id: 1,
    maLop: "IT101",
    tenLop: "ITS01",
    mon: "Database",
    khoa: "Khóa 13",
    nganh: "Kỹ thuật IT",
    giangVien: "Nguyễn Hải Trường",
    sinhVien: "40/45",
    trangThai: "Đang hoạt động",
    lich: "T2,T5 7:00 - 11:30 P.101 cơ sở 2 HCM",
  },
  {
    id: 2,
    maLop: "IT102",
    tenLop: "ITS02",
    mon: "Lập trình Web",
    khoa: "Khóa 13",
    nganh: "Kỹ thuật IT",
    giangVien: "Nguyễn Văn B",
    sinhVien: "35/45",
    trangThai: "Đang hoạt động",
    lich: "T3,T6 13:00 - 16:30 P.201 cơ sở 1 HCM",
  },
  {
    id: 3,
    maLop: "IT103",
    tenLop: "ITS03",
    mon: "Database",
    khoa: "Khóa 13",
    nganh: "Kỹ thuật IT",
    giangVien: "Nguyễn Hải Trường",
    sinhVien: "40/45",
    trangThai: "Đang hoạt động",
    lich: "T2,T4 8:00 - 11:30 P.301 cơ sở 2 HCM",
  },
  {
    id: 4,
    maLop: "IT104",
    tenLop: "ITS04",
    mon: "ASP.NET",
    khoa: "Khóa 13",
    nganh: "Kỹ thuật IT",
    giangVien: "Nguyễn Hải Trường",
    sinhVien: "40/45",
    trangThai: "Đang hoạt động",
    lich: "T4,T7 7:00 - 10:30 P.102 cơ sở 2 HCM",
  },
  {
    id: 5,
    maLop: "IT105",
    tenLop: "ITS05",
    mon: "Lập trình Mobile",
    khoa: "Khóa 13",
    nganh: "Kỹ thuật IT",
    giangVien: "Nguyễn Hải Trường",
    sinhVien: "40/45",
    trangThai: "Đang hoạt động",
    lich: "T3,T5 14:00 - 17:30 P.401 cơ sở 1 HCM",
  },
  {
    id: 6,
    maLop: "IT106",
    tenLop: "ITS06",
    mon: "Database",
    khoa: "Khóa 13",
    nganh: "Kỹ thuật IT",
    giangVien: "Nguyễn Hải Trường",
    sinhVien: "40/45",
    trangThai: "Chưa hoạt động",
    lich: "T2,T6 9:00 - 12:30 P.501 cơ sở 2 HCM",
  },
  {
    id: 7,
    maLop: "IT107",
    tenLop: "ITS07",
    mon: "Database",
    khoa: "Khóa 13",
    nganh: "Kỹ thuật IT",
    giangVien: "Nguyễn Hải Trường",
    sinhVien: "40/45",
    trangThai: "Chưa hoạt động",
    lich: "T4,T6 7:00 - 10:30 P.201 cơ sở 1 HCM",
  },
  {
    id: 8,
    maLop: "IT108",
    tenLop: "ITS08",
    mon: "Database",
    khoa: "Khóa 13",
    nganh: "Kỹ thuật IT",
    giangVien: "Nguyễn Hải Trường",
    sinhVien: "40/45",
    trangThai: "Chưa hoạt động",
    lich: "T3,T7 13:00 - 16:30 P.302 cơ sở 2 HCM",
  },
]

// Data sinh viên cho mỗi lớp
export const studentsInClass = {
  IT101: [
    {
      mssv: "IT101",
      hoTen: "Nguyễn Hải Trường",
      khoa: "Khóa 13",
      nganh: "Kỹ thuật IT",
      tongDiem: 7.0,
      trangThai: "Đang học",
    },
    {
      mssv: "IT102",
      hoTen: "Trần Văn Nam",
      khoa: "Khóa 13",
      nganh: "Kỹ thuật IT",
      tongDiem: 5.0,
      trangThai: "Đang học",
    },
    { mssv: "IT103", hoTen: "Lê Thị Hoa", khoa: "Khóa 13", nganh: "Kỹ thuật IT", tongDiem: 10, trangThai: "Đang học" },
    {
      mssv: "IT104",
      hoTen: "Phạm Minh Tuấn",
      khoa: "Khóa 13",
      nganh: "Kỹ thuật IT",
      tongDiem: 4.0,
      trangThai: "Đang học",
    },
    { mssv: "IT105", hoTen: "Võ Thị Mai", khoa: "Khóa 13", nganh: "Kỹ thuật IT", tongDiem: 8.0, trangThai: "Đang học" },
    {
      mssv: "IT106",
      hoTen: "Hoàng Văn Đức",
      khoa: "Khóa 13",
      nganh: "Kỹ thuật IT",
      tongDiem: 7.0,
      trangThai: "Đang học",
    },
    {
      mssv: "IT107",
      hoTen: "Ngô Thị Lan",
      khoa: "Khóa 13",
      nganh: "Kỹ thuật IT",
      tongDiem: 7.5,
      trangThai: "Đang học",
    },
    {
      mssv: "IT108",
      hoTen: "Đỗ Văn Hùng",
      khoa: "Khóa 13",
      nganh: "Kỹ thuật IT",
      tongDiem: 9.0,
      trangThai: "Đã nghỉ",
    },
  ],
  IT102: [
    {
      mssv: "IT201",
      hoTen: "Nguyễn Thị Hương",
      khoa: "Khóa 13",
      nganh: "Kỹ thuật IT",
      tongDiem: 8.5,
      trangThai: "Đang học",
    },
    {
      mssv: "IT202",
      hoTen: "Trần Minh Quân",
      khoa: "Khóa 13",
      nganh: "Kỹ thuật IT",
      tongDiem: 6.5,
      trangThai: "Đang học",
    },
  ],
}

export const studentsData = [
  {
    mssv: "20131",
    hoTen: "Nguyễn Hải Trường",
    khoa: "Khóa 13",
    khoaHoc: "Khoa CNTT",
    nganh: "Kỹ thuật IT",
    monLop: "Lập trình Web",
    giangVien: "Nguyễn Hải Trường",
    tongTinChi: 12,
    gpa: 4.0,
    trangThai: "Đang học",
    ngaySinh: "15/08/2002",
    dienThoai: "0987654321",
    email: "truong.nh@email.com",
    chuyenNganh: "Kỹ thuật IT",
    gpaTichLuy: "3.8 / 4.0",
    ngayTaoHoSo: "20/08/2020",
  },
  {
    mssv: "20132",
    hoTen: "Trần Văn Nam",
    khoa: "Khóa 13",
    khoaHoc: "Khoa CNTT",
    nganh: "Kỹ thuật IT",
    monLop: "Lập trình Web",
    giangVien: "Nguyễn Hải Trường",
    tongTinChi: 12,
    gpa: 4.0,
    trangThai: "Đang học",
    ngaySinh: "20/05/2002",
    dienThoai: "0912345678",
    email: "nam.tv@email.com",
    chuyenNganh: "Kỹ thuật IT",
    gpaTichLuy: "3.5 / 4.0",
    ngayTaoHoSo: "20/08/2020",
  },
  {
    mssv: "20133",
    hoTen: "Lê Thị Hoa",
    khoa: "Khóa 13",
    khoaHoc: "Khoa CNTT",
    nganh: "Kỹ thuật IT",
    monLop: "Lập trình Web",
    giangVien: "Nguyễn Hải Trường",
    tongTinChi: 12,
    gpa: 4.0,
    trangThai: "Đang học",
    ngaySinh: "10/03/2002",
    dienThoai: "0909876543",
    email: "hoa.lt@email.com",
    chuyenNganh: "Kỹ thuật IT",
    gpaTichLuy: "3.9 / 4.0",
    ngayTaoHoSo: "20/08/2020",
  },
  {
    mssv: "20134",
    hoTen: "Phạm Minh Tuấn",
    khoa: "Khóa 13",
    khoaHoc: "Khoa CNTT",
    nganh: "Kỹ thuật IT",
    monLop: "Lập trình Web",
    giangVien: "Nguyễn Hải Trường",
    tongTinChi: 12,
    gpa: 4.0,
    trangThai: "Đang học",
    ngaySinh: "25/12/2001",
    dienThoai: "0977123456",
    email: "tuan.pm@email.com",
    chuyenNganh: "Kỹ thuật IT",
    gpaTichLuy: "2.5 / 4.0",
    ngayTaoHoSo: "20/08/2020",
  },
  {
    mssv: "20135",
    hoTen: "Võ Thị Mai",
    khoa: "Khóa 13",
    khoaHoc: "Khoa CNTT",
    nganh: "Kỹ thuật IT",
    monLop: "Lập trình Web",
    giangVien: "Nguyễn Hải Trường",
    tongTinChi: 12,
    gpa: 4.0,
    trangThai: "Đang học",
    ngaySinh: "05/07/2002",
    dienThoai: "0966789012",
    email: "mai.vt@email.com",
    chuyenNganh: "Kỹ thuật IT",
    gpaTichLuy: "3.7 / 4.0",
    ngayTaoHoSo: "20/08/2020",
  },
  {
    mssv: "20136",
    hoTen: "Hoàng Văn Đức",
    khoa: "Khóa 13",
    khoaHoc: "Khoa CNTT",
    nganh: "Kỹ thuật IT",
    monLop: "Lập trình Web",
    giangVien: "Nguyễn Hải Trường",
    tongTinChi: 12,
    gpa: 4.0,
    trangThai: "Đang học",
    ngaySinh: "18/09/2002",
    dienThoai: "0955456789",
    email: "duc.hv@email.com",
    chuyenNganh: "Kỹ thuật IT",
    gpaTichLuy: "3.6 / 4.0",
    ngayTaoHoSo: "20/08/2020",
  },
  {
    mssv: "20137",
    hoTen: "Ngô Thị Lan",
    khoa: "Khóa 13",
    khoaHoc: "Khoa CNTT",
    nganh: "Kỹ thuật IT",
    monLop: "Lập trình Web",
    giangVien: "Nguyễn Hải Trường",
    tongTinChi: 12,
    gpa: 4.0,
    trangThai: "Đã nghỉ",
    ngaySinh: "30/11/2002",
    dienThoai: "0944321098",
    email: "lan.nt@email.com",
    chuyenNganh: "Kỹ thuật IT",
    gpaTichLuy: "3.2 / 4.0",
    ngayTaoHoSo: "20/08/2020",
  },
  {
    mssv: "20138",
    hoTen: "Đỗ Văn Hùng",
    khoa: "Khóa 13",
    khoaHoc: "Khoa CNTT",
    nganh: "Kỹ thuật IT",
    monLop: "Lập trình Web",
    giangVien: "Nguyễn Hải Trường",
    tongTinChi: 12,
    gpa: 4.0,
    trangThai: "Đã nghỉ",
    ngaySinh: "14/02/2002",
    dienThoai: "0933654321",
    email: "hung.dv@email.com",
    chuyenNganh: "Kỹ thuật IT",
    gpaTichLuy: "2.8 / 4.0",
    ngayTaoHoSo: "20/08/2020",
  },
]

export const bangDiemData = [
  {
    mon: "Lập trình Web",
    baiTap: 8.5,
    giuaKy: 9.0,
    cuoiKy: 9.5,
    chuyenCan: "100%",
    tbMon: 9.2,
    diemChu: "A+",
    gpaMon: 4.0,
  },
  {
    mon: "Cơ sở dữ liệu",
    baiTap: 7.0,
    giuaKy: 8.0,
    cuoiKy: 7.5,
    chuyenCan: "95%",
    tbMon: 7.6,
    diemChu: "B+",
    gpaMon: 3.5,
  },
  {
    mon: "Mạng máy tính",
    baiTap: 9.0,
    giuaKy: 8.5,
    cuoiKy: 9.0,
    chuyenCan: "100%",
    tbMon: 8.8,
    diemChu: "A",
    gpaMon: 3.8,
  },
]

export const lichSuDiemData = [
  {
    thoiGian: "20/05/2024 10:30 AM",
    nguoiThucHien: "Trần Anh Tuấn",
    monHoc: "Lập trình Web",
    thanhPhanDiem: "Cuối kỳ",
    diemCu: 9.0,
    diemMoi: 9.5,
  },
  {
    thoiGian: "18/05/2024 02:15 PM",
    nguoiThucHien: "Hệ thống",
    monHoc: "Cơ sở dữ liệu",
    thanhPhanDiem: "Giữa kỳ",
    diemCu: 7.5,
    diemMoi: 8.0,
  },
  {
    thoiGian: "15/05/2024 09:00 AM",
    nguoiThucHien: "Nguyễn Thị Mai",
    monHoc: "Mạng máy tính",
    thanhPhanDiem: "Bài tập",
    diemCu: 8.0,
    diemMoi: 9.0,
  },
  {
    thoiGian: "12/04/2024 11:45 AM",
    nguoiThucHien: "Trần Anh Tuấn",
    monHoc: "Lập trình Web",
    thanhPhanDiem: "Bài tập",
    diemCu: 8.0,
    diemMoi: 8.5,
  },
  {
    thoiGian: "05/03/2024 04:20 PM",
    nguoiThucHien: "Lê Văn Hùng",
    monHoc: "Cơ sở dữ liệu",
    thanhPhanDiem: "Chuyên cần",
    diemCu: 10,
    diemMoi: 9,
  },
]

export const giangVienList = ["Nguyễn Văn A", "Nguyễn Hải Trường", "Trần Văn B", "Lê Thị C", "Phạm Văn D"]

// Data giảng viên
export const giangVienData = [
  {
    id: "00001",
    maGiangVien: "00001",
    hoTen: "Nguyễn Hải Trường",
    gioiTinh: "Nam",
    ngaySinh: "15/08/1982",
    email: "truong.nh@example.edu",
    soDienThoai: "0987654321",
    hocVi: "Tiến sĩ",
    chucVu: "Giảng Viên",
    chuyenNganh: "Trí Tuệ Nhân Tạo & Học Máy",
    khoa: "Khoa Học Máy Tính",
    diaChi: "123 Example St, District 1, Ho Chi Minh City",
    ngayGiaNhap: "20/08/2010",
    tongSoLop: 42,
    trangThai: "Đang hoạt động",
    nganh: "Khoa CNTT",
    monPhuTrach: "Lập trình Web",
    soLopDangDay: 2,
    avatar: "/avatar-user-asian-male.jpg",
  },
  {
    id: "00002",
    maGiangVien: "00002",
    hoTen: "Trần Văn B",
    gioiTinh: "Nam",
    ngaySinh: "20/05/1985",
    email: "b.tran@example.edu",
    soDienThoai: "0912345678",
    hocVi: "Thạc sĩ",
    chucVu: "Giảng Viên",
    chuyenNganh: "Cơ sở Dữ liệu",
    khoa: "Khoa Học Máy Tính",
    diaChi: "456 Main St, District 3, Ho Chi Minh City",
    ngayGiaNhap: "15/09/2012",
    tongSoLop: 35,
    trangThai: "Đang hoạt động",
    nganh: "Khoa CNTT",
    monPhuTrach: "Database",
    soLopDangDay: 3,
    avatar: "/avatar-user-asian-male.jpg",
  },
  {
    id: "00003",
    maGiangVien: "00003",
    hoTen: "Lê Thị C",
    gioiTinh: "Nữ",
    ngaySinh: "10/03/1988",
    email: "c.le@example.edu",
    soDienThoai: "0909876543",
    hocVi: "Tiến sĩ",
    chucVu: "Trưởng Bộ Môn",
    chuyenNganh: "Mạng Máy Tính",
    khoa: "Khoa Học Máy Tính",
    diaChi: "789 Park Ave, District 7, Ho Chi Minh City",
    ngayGiaNhap: "01/10/2015",
    tongSoLop: 28,
    trangThai: "Đang hoạt động",
    nganh: "Khoa CNTT",
    monPhuTrach: "Mạng Máy Tính",
    soLopDangDay: 1,
    avatar: "/avatar-user-asian-male.jpg",
  },
  {
    id: "00004",
    maGiangVien: "00004",
    hoTen: "Phạm Văn D",
    gioiTinh: "Nam",
    ngaySinh: "25/12/1980",
    email: "d.pham@example.edu",
    soDienThoai: "0977123456",
    hocVi: "Thạc sĩ",
    chucVu: "Giảng Viên",
    chuyenNganh: "Lập trình Mobile",
    khoa: "Khoa Học Máy Tính",
    diaChi: "321 Tech St, District 2, Ho Chi Minh City",
    ngayGiaNhap: "05/11/2011",
    tongSoLop: 30,
    trangThai: "Đang hoạt động",
    nganh: "Khoa CNTT",
    monPhuTrach: "Lập trình Mobile",
    soLopDangDay: 2,
    avatar: "/avatar-user-asian-male.jpg",
  },
  {
    id: "00005",
    maGiangVien: "00005",
    hoTen: "Nguyễn Văn A",
    gioiTinh: "Nam",
    ngaySinh: "18/06/1983",
    email: "a.nguyen@example.edu",
    soDienThoai: "0966789012",
    hocVi: "Tiến sĩ",
    chucVu: "Giảng Viên",
    chuyenNganh: "ASP.NET",
    khoa: "Khoa Học Máy Tính",
    diaChi: "654 Dev Blvd, District 1, Ho Chi Minh City",
    ngayGiaNhap: "12/07/2009",
    tongSoLop: 50,
    trangThai: "Không hoạt động",
    nganh: "Khoa CNTT",
    monPhuTrach: "ASP.NET",
    soLopDangDay: 0,
    avatar: "/avatar-user-asian-male.jpg",
  },
  {
    id: "00006",
    maGiangVien: "00006",
    hoTen: "Hoàng Thị E",
    gioiTinh: "Nữ",
    ngaySinh: "30/11/1987",
    email: "e.hoang@example.edu",
    soDienThoai: "0955456789",
    hocVi: "Thạc sĩ",
    chucVu: "Giảng Viên",
    chuyenNganh: "Lập trình Web",
    khoa: "Khoa Học Máy Tính",
    diaChi: "987 Code Lane, District 5, Ho Chi Minh City",
    ngayGiaNhap: "22/03/2013",
    tongSoLop: 25,
    trangThai: "Không hoạt động",
    nganh: "Khoa CNTT",
    monPhuTrach: "Lập trình Web",
    soLopDangDay: 0,
    avatar: "/avatar-user-asian-male.jpg",
  },
  {
    id: "00007",
    maGiangVien: "00007",
    hoTen: "Võ Minh F",
    gioiTinh: "Nam",
    ngaySinh: "14/02/1984",
    email: "f.vo@example.edu",
    soDienThoai: "0944321098",
    hocVi: "Tiến sĩ",
    chucVu: "Giảng Viên",
    chuyenNganh: "Database",
    khoa: "Khoa Học Máy Tính",
    diaChi: "147 Data St, District 10, Ho Chi Minh City",
    ngayGiaNhap: "08/04/2014",
    tongSoLop: 20,
    trangThai: "Không hoạt động",
    nganh: "Khoa CNTT",
    monPhuTrach: "Database",
    soLopDangDay: 0,
    avatar: "/avatar-user-asian-male.jpg",
  },
  {
    id: "00008",
    maGiangVien: "00008",
    hoTen: "Đỗ Thị G",
    gioiTinh: "Nữ",
    ngaySinh: "05/09/1986",
    email: "g.do@example.edu",
    soDienThoai: "0933654321",
    hocVi: "Thạc sĩ",
    chucVu: "Giảng Viên",
    chuyenNganh: "Lập trình Web",
    khoa: "Khoa Học Máy Tính",
    diaChi: "258 Web Ave, District 1, Ho Chi Minh City",
    ngayGiaNhap: "15/06/2016",
    tongSoLop: 15,
    trangThai: "Đang hoạt động",
    nganh: "Khoa CNTT",
    monPhuTrach: "Lập trình Web",
    soLopDangDay: 1,
    avatar: "/avatar-user-asian-male.jpg",
  },
]

// Data lịch dạy
export const lichDayData = [
  {
    id: 1,
    monHoc: "Database",
    lop: "CNTT-K13",
    ngayDay: "Thứ 2",
    thoiGian: "13:00 - 16:30",
    phongHoc: "P.403 cơ sở 2, HCM",
    giangVien: "Nguyễn Hải Trường",
    thoiLuong: 5,
    ngay: "2025-11-17", // Thứ 2
    gioBatDau: "13:00",
    gioKetThuc: "16:30",
    giangVienId: "00001",
  },
  {
    id: 2,
    monHoc: "Lập trình Web",
    lop: "CNTT-K13",
    ngayDay: "Thứ 3",
    thoiGian: "08:00 - 11:30",
    phongHoc: "P.201 cơ sở 1, HCM",
    giangVien: "Nguyễn Hải Trường",
    thoiLuong: 4,
    ngay: "2025-11-18", // Thứ 3
    gioBatDau: "08:00",
    gioKetThuc: "11:30",
    giangVienId: "00001",
  },
  {
    id: 3,
    monHoc: "Database",
    lop: "CNTT-K14",
    ngayDay: "Thứ 4",
    thoiGian: "14:00 - 17:30",
    phongHoc: "P.301 cơ sở 2, HCM",
    giangVien: "Trần Văn B",
    thoiLuong: 4,
    ngay: "2025-11-19", // Thứ 4
    gioBatDau: "14:00",
    gioKetThuc: "17:30",
    giangVienId: "00002",
  },
  {
    id: 4,
    monHoc: "Lập trình Mobile",
    lop: "CNTT-K13",
    ngayDay: "Thứ 5",
    thoiGian: "09:00 - 12:30",
    phongHoc: "P.401 cơ sở 1, HCM",
    giangVien: "Phạm Văn D",
    thoiLuong: 4,
    ngay: "2025-11-20", // Thứ 5
    gioBatDau: "09:00",
    gioKetThuc: "12:30",
    giangVienId: "00004",
  },
]

// Danh sách ngành
export const nganhList = ["Khoa CNTT", "Khoa Điện", "Khoa Cơ Khí"]

// Danh sách môn học
export const monHocList = ["Lập trình Web", "Database", "ASP.NET", "Lập trình Mobile", "Mạng Máy Tính"]
